name: build

# Run this workflow every time a new commit pushed to your repository
on: [push, pull_request]

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - run: yarn build
